"""empty message

Revision ID: 3a5a547fc628
Revises: 
Create Date: 2021-07-21 16:05:20.014093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a5a547fc628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('cwa', sa.Float(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('course_diff', sa.Float(), nullable=True),
    sa.Column('pred_score', sa.Float(), nullable=True),
    sa.Column('act_score', sa.Float(), nullable=True),
    sa.Column('study_hour', sa.Float(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
